### ISSUE TITLE
Does Blossom support Subprojects?

### ISSUE THREAD

**Issue by Andre601** [KyoriPowered/blossom#8]
I try to use blossom in the `build.gradle`'s `subprojects` block, but when I try to do so does it not alter the provided String at all.

Could it be, that blossom doesn't work with Javadoc comments or ignores package-summaries?

**Comment by jpenilla** [comment]
I use blossom within subprojects without issue. Make sure you are actually applying the blossom plugin to your subprojects and not just the root project.

As far as Javadoc, blossom doesn't make any distinction about where it replaces tokens, however replacements in Javadoc may not work as expected given how blossom works. I have not tested whether replacements in Javadoc work, but if not I would assume the underlying cause is similar to that of #9. If that is the case, please open a separate issue.
